use super::setup::SetupCommand;

/// All CLI subcommands. Each variant maps 1:1 to a service method.
pub enum CliCommand {
    Array,
    Disks,
    Docker,
    DockerLogs {
        id: String,
        tail: Option<i64>,
    },
    Vms,
    Server,
    Info,
    Shares,
    Notifications,
    LogFiles,
    LogFile {
        path: String,
        lines: Option<i64>,
        start_line: Option<i64>,
    },
    Services,
    Network,
    Ups,
    UpsConfig,
    Metrics,
    Plugins,
    ParityHistory,
    Vars,
    Registration,
    Flash,
    Rclone,
    RemoteAccess,
    Connect,
    Online,
    SystemTime,
    InstalledUnraidPlugins,
    IsSsoEnabled,
    PublicOidcProviders,
    OidcProviders,
    OidcConfiguration,
    ApiKeys,
    ApiKeyPossibleRoles,
    ApiKeyPossiblePermissions,
    GetAvailableAuthActions,
    GetApiKeyCreationFormSchema,
    Config,
    Settings,
    Display,
    Customization,
    InternalBootContext,
    Doctor,
    Setup(SetupCommand),
}
